const message = {
  hsnSuccess: "HSN details get successfully.",
  brandSuccess: "Brand details get successfully.",
  manufacturerSuccess: "Manufacturer details get successfully.",
  invalidBrandId: "Invalid brand id.",
  invalidUOMId: "Invalid uom id.",
  invalidPaintTypeId: "Invalid paintType id.",
  invalidFinishTypeId: "Invalid finishType id.",
  invalidManufacturerId: "Invalid manufacturer id.",
  invalidHsnId: "Invalid hsn id.",
  invalidColorId: "Invalid color id",
  invalidCategoryId:"Invalid Category id",
  invalidSubCategoryId:"Invalid SubCategory id",
  invalidBasePaintOneProductId:"Invalid Base paint One Product id",
  invalidBasePaintTwoProductId:"Invalid Base paint Two Product id",
  invalidBasePaintOneUomId:"Invalid Base paint One UOM id",
  invalidBasePaintTwoUomId:"Invalid Base paint Two UOM id",
  invalidTinterProductId:"Invalid Tinter Product Id",
  prodcutExist: "This product already exist.",
  sellingPrice: "Selling price should not be greater than MRP.",
  productAddSuccess: "Product added successfully.",
  productBulkAddSuccess: "Products added successfully.",
  productListSuccess: "Product list get successfully.",
  noProductList:"Product List Not Found",
  noProductFound:"Product Not Found",
  productDetailSuccess: "Product details get successfully.",
  productUpdateSuccess: "Product details updated successfully.",
  productDeleted: "Product deleted successfully.",
  multipleProductsDeleted:"Multiple Products deleted successfully.",
  categoryTaken:"Category does not exist",
  subcategoryNotExist:"SubCategory Not exists",
  subchildcategoryNotExist:"Sub Child Category Not Exist",
  productFailed:"Failed to add the product",
  productUpdationFailed:"Failed to update the product"
};

export default message;
