const message = {
  correctPin: `invalid pin code`,
  bulkCompanyUpload: `successfully uploaded all the companies`,
  noCompanyFound: `Company not found`,
  companyExist: `Company already exists`,
  addressExist: `Address already exists`,
  companyAddFailed: `Failed to add new Company`,
  CompanySuccess: `Company Added successfully`,
  AddressSuccess: `Address Added successfully`,
  failedDelete: `Failed to delete company`,
  updateFailed: `Failed to update the company`,
  updateSuccess: `Company updated successfully`,
  companydelete: `Company deleted successfully`,
  companiesBulkSuccess: `Bulk upload company successfully`,
  companyDetail: "Successfully fetched company details",
  emailPhoneExists: "Email or phone already taken",
  addAddFailed: "failed to add the address",
  selfCompanyNotFound: "Self or ERP Company Not Found",
  companyDleteFailed: `failed to delete company`,
  deleteCompanySuccess: `successfully deleted company`,
  logoChangeSuccess: `Logo changed successfully`,
  deleteAllSuccess: `Successfully deleted all the companies`,
  addCategory: `Please provide category`,
  addtags: "Please provide tags",
  emailExists: "email already taken",
  phoneExists: "Phone already taken",
  addressDeleteFailed: "address delete failed",
};
export default message;
