const message = {
  alreadyBrand: "Brand already exists.",
  alreadyColor: "Brand already exists.",
  brandSuccess: "Brand added successfully.",
  colorSuccess: "Color added successfully.",
  brandBulkSuccess: "Brands added successfully.",
  brandListSuccess: "Brand list get successfully.",
  brandDetailSuccess: "Brand details get successfully.",
  brandUpdateSuccess: "Brand details updated successfully.",
  brandDeleteSuccess: "Brand deleted successfully.",
  brandNotFound:"Brand Not Found",
  alreadyClass: "Class already exists.",
  classSuccess: "Class added successfully.",
  classBulkSuccess: "Classes added successfully.",
  classListSuccess: "Class list get successfully.",
  classDetailSuccess: "Class details get successfully.",
  classUpdateSuccess: "Class details updated successfully.",
  classDeleteSuccess: "Class deleted successfully.",
  alreadyCategory: "Category already exists.",
  categorySuccess: "Category added successfully.",
  categoryBulkSuccess: "Categories added successfully.",
  categoryListSuccess: "Category list get successfully.",
  categoryDetailSuccess: "Category details get successfully.",
  categoryUpdateSuccess: "Category details updated successfully.",
  categoryDeleteSuccess: "Category deleted successfully.",
  alreadySubCategory: "Sub category already exists.",
  subCategorySuccess: "Sub category added successfully.",
  subCategoryBulkSuccess: "Sub categories added successfully.",
  subCategoryListSuccess: "Sub category list get successfully.",
  subCategoryDetailSuccess: "Sub category details get successfully.",
  subCategoryUpdateSuccess: "Sub category details updated successfully.",
  subCategoryDeleteSuccess: "Sub category deleted successfully.",
  alreadySubChildCategory: "Sub child category already exists.",
  subChildCategorySuccess: "Sub child category added successfully.",
  subChildCategoryBulkSuccess: "Sub child categories added successfully.",
  subChildCategoryListSuccess: "Sub child category list get successfully.",
  subChildCategoryDetailSuccess: "Sub child category details get successfully.",
  subChildCategoryUpdateSuccess:
    "Sub child category details updated successfully.",
  subChildCategoryDeleteSuccess: "Sub child category deleted successfully.",
  alreadyManufacture: "Manufacture already exists.",
  manufactureSuccess: "Manufacture added successfully.",
  manufactureBulkSuccess: "Manufactures added successfully.",
  manufactureListSuccess: "Manufacture list get successfully.",
  manufactureDetailSuccess: "Manufacture details get successfully.",
  manufactureUpdateSuccess: "Manufacture details updated successfully.",
  manufactureDeleteSuccess: "Manufacture deleted successfully.",
  alreadyAutopart: "Auto part already exists.",
  autopartSuccess: "Auto part added successfully.",
  autopartBulkSuccess: "Auto parts added successfully.",
  autopartListSuccess: "Auto part list get successfully.",
  autopartDetailSuccess: "Auto part details get successfully.",
  autopartUpdateSuccess: "Auto part details updated successfully.",
  autopartDeleteSuccess: "Auto part deleted successfully.",
  colorListSuccess: "Color list get successfully.",
  colorDeleteSuccess: "color deleted successfully.",
  noTinterList:"No Tinter Products Found",
  alreadyFinishType: "Finish Type already exists.",
  finishTypeUpdateSuccess: "Finish Type updated successfully.",
  finishTypeDeleteSuccess: "Finish Type deleted successfully.",
  alreadyPaintType: "Paint Type already exists.",
  paintTypeDeleteSuccess: "Paint Type deleted successfully.",
  alreadyUOM: "UOM already exists.",
  finishTypeSuccess:"Finish Type created successfully",
  finishTypeListSuccess: "Finish Type list get successfully.",
  paintTypeSuccess:"Paint Type created successfully",
  paintTypeUpdateSuccess: "Paint Type updated successfully.",
  paintTypeListSuccess: "Paint Type list get successfully.",
  uomSuccess:"UOM created successfully",
  uomUpdateSuccess: "UOM updated successfully.",
  uomListSuccess: "UOM list get successfully.",
  uomDeleteSuccess: "UOM deleted successfully.",
  noCategory:"Category Not Found"
} 

export default message;
